# Generated by Django 4.1.7 on 2023-03-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_m", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="active_switch",
            field=models.BooleanField(
                default=True,
                help_text="Статус задачи, снять галочку для завершения, установить для продолжения работ",
            ),
        ),
        migrations.AddField(
            model_name="tasks",
            name="status_z",
            field=models.CharField(
                default="В работе",
                help_text="Статус задачи, комментарий к завершению",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="tasks",
            name="time_nach_z",
            field=models.DateTimeField(auto_now=True, help_text="Время начала"),
        ),
        migrations.AddField(
            model_name="tasks",
            name="time_zav_z",
            field=models.DateTimeField(auto_now=True, help_text="Время завершения"),
        ),
    ]
