# Generated by Django 4.1.7 on 2023-03-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "task_m",
            "0002_tasks_active_switch_tasks_status_z_tasks_time_nach_z_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="projects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Задача в проекте",
                related_name="task_in_project",
                to="task_m.projects",
            ),
        ),
    ]
