# Generated by Django 4.1.7 on 2023-03-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_m", "0003_tasks_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="time_dedlin_proj",
            field=models.DateTimeField(
                auto_now=True, help_text="Время на исполнение проекта"
            ),
        ),
        migrations.AddField(
            model_name="tasks",
            name="time_dedlin_task",
            field=models.DateTimeField(
                auto_now=True, help_text="Время на исполнение задачи"
            ),
        ),
    ]
