# Generated by Django 4.1.7 on 2023-03-12 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("task_m", "0004_projects_time_dedlin_proj_tasks_time_dedlin_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="time_dedlin_proj",
            field=models.DateTimeField(help_text="Время на исполнение проекта"),
        ),
        migrations.RemoveField(
            model_name="projects",
            name="users",
        ),
        migrations.AlterField(
            model_name="tasks",
            name="time_dedlin_task",
            field=models.DateTimeField(help_text="Время на исполнение задачи"),
        ),
        migrations.AddField(
            model_name="projects",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Пользователь выполняющий задачу",
                null=True,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
