# Generated by Django 4.1.7 on 2023-03-14 20:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_m", "0006_tasks_avtor_tasks_plan_data_tasks_soderzhanie_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltasks",
            name="plan_data",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="plan_data",
        ),
        migrations.AlterField(
            model_name="historicaltasks",
            name="time_dedlin_task",
            field=models.DateTimeField(
                blank=True,
                help_text="Время на исполнение задачи",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.datetime(
                            2023,
                            3,
                            14,
                            20,
                            14,
                            16,
                            323327,
                            tzinfo=datetime.timezone.utc,
                        )
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="time_dedlin_task",
            field=models.DateTimeField(
                blank=True,
                help_text="Время на исполнение задачи",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.datetime(
                            2023,
                            3,
                            14,
                            20,
                            14,
                            16,
                            323327,
                            tzinfo=datetime.timezone.utc,
                        )
                    )
                ],
            ),
        ),
    ]
