# Generated by Django 4.1.7 on 2023-03-15 18:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_m", "0007_remove_historicaltasks_plan_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="active_switch_prj",
            field=models.BooleanField(
                default=True,
                help_text="Статус проекта, снять галочку для завершения, установить для продолжения работ",
            ),
        ),
        migrations.AddField(
            model_name="projects",
            name="time_zav",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="historicaltasks",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Новая"),
                    ("PLANNED", "Planiruemaya"),
                    ("INPROGRESS", "V_rabote"),
                    ("COMPLETED", "Zavershena"),
                ],
                default="Выбрать",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="historicaltasks",
            name="status_z",
            field=models.CharField(
                choices=[("V_rabote", "В работе"), ("Vozvr", "Возвращена в работу")],
                default="В работе",
                help_text="Статус задачи, комментарий к завершению",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="historicaltasks",
            name="time_dedlin_task",
            field=models.DateTimeField(
                blank=True,
                help_text="Время на исполнение задачи",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.datetime(
                            2023,
                            3,
                            15,
                            18,
                            45,
                            50,
                            377804,
                            tzinfo=datetime.timezone.utc,
                        )
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="time_dedlin_proj",
            field=models.DateTimeField(
                blank=True,
                help_text="Время на исполнение проекта",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.datetime(
                            2023,
                            3,
                            15,
                            18,
                            45,
                            50,
                            376800,
                            tzinfo=datetime.timezone.utc,
                        )
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Новая"),
                    ("PLANNED", "Planiruemaya"),
                    ("INPROGRESS", "V_rabote"),
                    ("COMPLETED", "Zavershena"),
                ],
                default="Выбрать",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="status_z",
            field=models.CharField(
                choices=[("V_rabote", "В работе"), ("Vozvr", "Возвращена в работу")],
                default="В работе",
                help_text="Статус задачи, комментарий к завершению",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="time_dedlin_task",
            field=models.DateTimeField(
                blank=True,
                help_text="Время на исполнение задачи",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.datetime(
                            2023,
                            3,
                            15,
                            18,
                            45,
                            50,
                            377804,
                            tzinfo=datetime.timezone.utc,
                        )
                    )
                ],
            ),
        ),
    ]
