# Generated by Django 4.1.7 on 2023-03-16 18:39

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("task_m", "0010_projects_soderzhanie_p_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltasks",
            name="status_z",
            field=models.CharField(
                choices=[
                    ("V_rabote", "В работе"),
                    ("Vozvr", "Возвращена в работу"),
                    ("COMPLETED", "Завершить"),
                ],
                default="В работе",
                help_text="Статус задачи, комментарий к завершению",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="historicaltasks",
            name="time_dedlin_task",
            field=models.DateTimeField(
                blank=True,
                help_text="Время на исполнение задачи(пример 15.03.2023)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.datetime(
                            2023,
                            3,
                            16,
                            18,
                            39,
                            22,
                            477779,
                            tzinfo=datetime.timezone.utc,
                        )
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="active_switch_prj",
            field=models.BooleanField(
                default=True,
                help_text="Статус проекта, снять галочку для приостановки, установить для продолжения работ",
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="soderzhanie_p",
            field=models.TextField(
                default="Содержание", help_text="Цель проекта", max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="time_dedlin_proj",
            field=models.DateTimeField(
                blank=True,
                help_text="Время на исполнение проекта",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.datetime(
                            2023,
                            3,
                            16,
                            18,
                            39,
                            22,
                            476776,
                            tzinfo=datetime.timezone.utc,
                        )
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Пользователь выполняющий проект",
                null=True,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="status_z",
            field=models.CharField(
                choices=[
                    ("V_rabote", "В работе"),
                    ("Vozvr", "Возвращена в работу"),
                    ("COMPLETED", "Завершить"),
                ],
                default="В работе",
                help_text="Статус задачи, комментарий к завершению",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="time_dedlin_task",
            field=models.DateTimeField(
                blank=True,
                help_text="Время на исполнение задачи(пример 15.03.2023)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.datetime(
                            2023,
                            3,
                            16,
                            18,
                            39,
                            22,
                            477779,
                            tzinfo=datetime.timezone.utc,
                        )
                    )
                ],
            ),
        ),
    ]
